resurrecting-open-source-projects/scrot

src/options.c

For example, passing `-t` (thumbnail) without an argument would
previously both print that required arg is missing *and* continue saving
a screenshot!

Fail and do nothing if options parsing fails

---

src/main.c

Ref: https://bugs.launchpad.net/ubuntu/+source/scrot/+bug/148659
The default format, without user intervention, is PNG.

Fix: scrot can't save files without extension

---

configure.ac
src/main.c
src/options.c
src/scrot.h

Autotools say: "Don’t make the mistake of including config.h in a public header file if your project installs libraries and header files as part of your product set." and that mistake was made by giblib.
Add prefix SCROT_ to config.h
Evaluate the return of system() call.

Fix build warnings.

---

configure.ac

This check will avoid mistakes from users.

Added a check for autoconf-archive presence

---

man/scrot.1
man/scrot.txt
src/main.c
src/options.c

I move between multiple computers and save screenshots to a folder that is synchronized between them with Syncthing. This is handy when I'm writing documentation on one computer and taking screenshots of whatever I'm documenting on the other. 
Problem: how to tell which screenshot came from what system?
This PR adds a `$a` format flag that adds the system's hostname to the file name.
I picked "a" because hostnAme (h and n were already in use).

adds option to embed hostname in output file name

---

man/scrot.1
man/scrot.txt
src/main.c
src/options.c
src/options.h

This new option allows us to define the type of line and its width.
Examples:
```bash
scrot  --select --line style=dash
scrot --select --line width=3
scrot --select --line style=dash,width=3
```
Note: use `getsubopt (glibc >= 2.12)` which is available since 2010 so I do not think we should verify this version with autotool.

New option: --line, selection line style

---

man/scrot.1
man/scrot.txt
src/Makefile.am
src/main.c
src/note.c
src/note.h
src/options.c
src/options.h
src/scrot.h
src/structs.h

Alpha testing.
New option: `-n` or `--note`
```bash
./scrot -n "-f '/usr/share/fonts/TTF/DejaVuSans-Bold/30' -x 10 -y 20 -t 'test color with alpha' -c 232,91,44,150" -s
-f 'font_name/size' (Imlib2 API)
-t 'text'
-x position x (optional)
-y position y (optional)
-c color r,g,b,a (optional)
```
TODO:
~~- [ ] background color, draw rectangle~~

Implemented draw text.

---

.gitignore

This PR adds a `.gitignore` file to reduce risk of accidentally committing auto-generated files.

adds gitignore for to ignore autogenerated files

---

src/main.c

Hi
When _scrot_ is used with the selection option, executed through a keyboard shortcut, there is no indicator that _scrot_ is running waiting for the selection by the user.
This PR change the mouse cursor to indicate the selection mode.
I don't know why this was not implemented from the beginning.
If the community agrees we merge it.
Note: this PR does not affect the capture of the mouse.
Regards.

Change the cursor to indicate the selection mode.

---

src/getopt.c

The patches applied to pkgsrc to fix the warnings in `getopt.c` is shared here.
1. Fix the missing `string.h` when building in NetBSD
It seems `string.h` was conditionally included and was causing the compiler to spit out warnings. `string.h` is now unconditionally included to prevent this issues.
2. Fix the ambiguous `else` for the `if` in line 689
This has been fixed by adding the correct braces to the `if` condition in line 689.
This pull request addresses #26 in the issue tracker.

Fix warnings in getopt.c

---

src/main.c

Hi,
This PR fix #28 
The new version of `GCC >=8.0` includes the `-Wstringop-truncation` flag.
This flag alerts the possibility that a string ends without the null character.
When variable `*c` is not equal to the characters `$` or `\` then the compiler cannot know if the next character is null and therefore throws the warning.
I opted to manually concatenate the buffer.
@eribertomota merge it whenever you want.

Fix GCC >=8.0 warning: -Wstringop-truncation 

---

man/scrot.1
man/scrot.txt
src/imlib.c
src/main.c
src/options.c
src/options.h

Adds option  _-D_, _--display_ and mirrors other display arguments in common X programs e.g. _xeyes_.
This is good for scripting and other monitoring when using _ssh_ or _screen_ and the **DISPLAY** environment variable is not set.

Add Display Option.

---

src/main.c
src/scrot.h

This fix #39  
I used `scrot_grab_focused()` as an base. 
The screenshot shows the command used (`scrot -a 0,0,1920,1080 -p`) to test, and as shown, the mouse appears.

Fix issue#39

---

src/options.c

- options_parse_required_number(): requires that parameter is not null.
- options_parse_autoselect(): validate parameter format.

Fix required number. Fix autoselect.

---

.github/workflows/full-check.yml
man/scrot.txt
src/Makefile.am
src/main.c
src/options.c
src/options.h
src/scrot.h

New option: `--stack` or `-k`
Dependencies:
- Library: libXcomposite (X11)
- Runtime: Composite Window Manager. Automatic detected.

New Feature: capture stack/overlapping windows.

---

.github/workflows/full-check.yml
README.md
src/Makefile.am
src/scrot.h

With GNUld --as-needed, the libXcursor linkage is discarded, so nothing that libXcursor provides is actually required in scrot.

Remove libXcursor references, add one libXcomposite reference

---

src/note.c

The functions next_space() and next_not_space() must detect end of C string
character.

Fix SIGSEGV, option --note

---

src/imlib.c

Currently if running on a server without DISPLAY set, it will cause segment fault.

Fix SIGSEGV, if running without DISPLAY

---

src/imlib.c
src/main.c

This happens because the function `init_x_and_imlib` is reentrant from
`scrot_grab_shot_multi` generating a  double record in `atexit` thus calling `XCloseDisplay` 2 times.

Fixed segfault: --multidisp option

---

man/scrot.txt
src/main.c
src/options.c
src/options.h
src/scrot.h

This is a new feature, it allows discriminating between windows only those that match the class name.
At the moment it is only useful for the `--stack` option, I point it out in the help.
For example, detect only windows with the "XTerm" class:
```
scrot --stack --class "XTerm"
```
I designed the function so that in the future it can be used for other parameters (associative option).
It would be necessary to update the man-page.

Option --class: discriminate windows by class name

---

src/main.c

Not record pointer if there is a selection area because it is busy on that.
This prevents the cursor appears partially in the capture.

 Do not record pointer when selecting an area

---

man/scrot.txt
src/Makefile.am
src/main.c
src/options.c
src/options.h
src/scrot.h
src/scrot_selection.c
src/scrot_selection.h
src/selection_classic.c
src/selection_classic.h
src/selection_edge.c
src/selection_edge.h

WIP #60, #37 
Big refactoring of the `scrot_sel_and_grab_image()` function
- New `mode` specifier for `--line` option, supports `classic` (default) and `edge`
- New files: `scrot_selection.{c,h}`, `selection_edge.{c,h}`, `selection_classic.{c,h}`
- Use stdbool.h (C99)
More info: https://github.com/resurrecting-open-source-projects/scrot/issues/60#issuecomment-723329026
Note:  I prefixed the branch `wip-` because it is only to work, not to merge with `master`, for that I'm going to create another branch and use `--squash` to create a single commit message.

Support various modes of drawing selection

---

src/main.c

Hello,
I tried to compile scrot on OpenBSD/Sparc64 and it ran into compile errors due to two inline declarations that aren't strictly c99.
```
main.c: In function 'scrot_grab_mouse_pointer':
main.c:257: error: 'for' loop initial declaration used outside C99 mode
main.c: In function 'scrot_grab_stack_windows':
main.c:850: error: 'for' loop initial declaration used outside C99 mode
```
This pull request moves the declaration out of the for loops.
This fixes the compilation on sparc64 without relaxing the C standard.

Fix compilation on Sparc64 (on OpenBSD)

---

src/main.c
src/options.c

Fix various typos

---

man/scrot.txt
src/main.c
src/options.c

Give the WM time to update the hidden area of the window.
When using the `scrot --select --border` option and clicking on a window that is hidden behind another,  this happens:
This commit fixes that, waiting for the `FocusChangedMask` event or if it timed out.

Wait for the window to finish rising

---

man/scrot.txt
src/main.c
src/options.c
src/options.h

Examples:
```bash
scrot --script "tint(red=100,green=10,blue=10,alpha=30,tint=233);"
scrot --script "colormod(brightness=0.5);"
scrot --script "colormod(contrast=0.2);"
```

Support script Imlib2 commands

---

src/selection_edge.c

Useful for `edge` selection mode.
Even though scrot has the `dock` property, some composite window managers
allow shadows to be drawn on them but allow you to exclude them according
to the name assigned to the property WM_CLASS.

Setting WM_CLASS property

---

src/scrot_selection.c
src/scrot_selection.h

When **selecting** an area to screenshot from the **bottom left** corner to the **top right** corner, I noticed the cursor icon was a **south-east** angle one, which was kind of funny-looking, so I downloaded the source code and add more variables for cursor icons and conditions to display which.
I've also recompiled and installed the modified package on my end, and it worked out great!

Added 3 other corner cursors when selecting an area

---

README.md
configure.ac
src/Makefile.am
src/main.c
src/note.c
src/note.h
src/options.c
src/scrot.h
src/slist.c
src/slist.h
src/utils.c
src/utils.h

giblib usage in scrot was primarily for simple wrappers around
imlib by setting context then calling/returning the wrapped
imlib_image_* calls. by reworking these calls, we can remove
the giblib dependency.
configure.ac: check for strdup
utils: implement strdup
slist: simple, dump singly-linked list
Makefile: add utils&slist
scrot: header updates
options: eprintf and strdup
main: remove simple wrappers with context + imlib calls

Decouple giblib from scrot: resurrect/retire giblib as well? #22

---

src/Makefile.am

- Debug symbols flag : -g
- Optimization flag  : -O3
It allows each maintainer of a particular distribution to indicate the
compilation mode that their standard requires, and it allows a
particular user to configure theirs.
Closes: #54

Remove compiler options

---

README.md

Hi, I've polished the README.md file. 
The most inconsequential change is the correct English spelling and structure, but there is more to this patch:
I've removed redundant statements. For instance, repeating that scrot stands for (SCReenshOT) is jarring. 
The original text  also states that imlib2 is used to save images, procceeds to mention that imlib2 is used to support multiple image formats, and then lists support for multiple image formats among its features. That's a 3-way repetition.
There was one incorrect statement. scrot doesn't seem to depend on libtool directly. I'm not very good with autotools, so if this is wrong we can fix it.
I've clarified the build instructions. There was no mention that `make distclean` doesn't fully clean up the project, and that to do that …

README.md: partial rewrite

---

.cirrus.yml

This automates build testing in the following platforms:
- Alpine Linux (musl Linux)
- Debian Linux (glibc Linux)
- FreeBSD
- MacOS
Multiple branches of Debian are used to cover toolchains ranging from ancient to bleeding edge.
It would be very easy to add testing to this in the future, but
currently scrot has no tests.
If this is merged in, @eribertomota will have to add the
[Cirrus CI](https://cirrus-ci.org/) application to his github account to enable it.
Cirrus can be seen in action at this URL: https://cirrus-ci.com/github/guijan/scrot/add-cirrus

add the Cirrus CI system

---

src/scrot.h

https://gcc.gnu.org/onlinedocs/gcc/Variable-Attributes.html
This macro exists to turn a few GCC/Clang specific extensions into no-ops if on another compiler, but scrot isn't using any such extensions.

remove unused __attribute__ macro

---

configure.ac
src/options.c

scrot is an old program but strndup() is standardized by POSIX 2008 and widely adopted. It's time to make it obligatory.

make strndup obligatory

---

src/note.c

new_text is a reimplementation of strndup, which is soon to be made obligatory by #102.

use strndup to provide new_text

---

src/options.c

Right now I am not with my main computer.
TODO.

getopt: replace literal constant with named value

---

man/scrot.txt

I've made changes to the txt2man manual.
The most innocuous ones are the minor English corrections and making the description like the README.md file in the source tree.
I've changed the line length to be at most 80 characters always, 80 being the "standard" amount of columns in a terminal.
The options are sorted alphabetically and case insensitively by their short forms. The upper case short options don't all come first.
The synopsis is now a complete summary of all the flags.
Some flags which didn't previously list an argument but took one now have the fact that they take arguments clearly specified. I'm not 100% sure I got all of them though.
The manual now uses exclusively the short options while explaining its flags, to encourage their use.
This isn't all but that's the gist of it.

polish the txt2man manual

---

src/options.c
src/scrot.h

The old help text is outdated and a duplicate of the manual. This patch brings the help flag in line with the style popular among Suckless and BSD utilities:
```
$ src/scrot -h
usage:  scrot [-bcfhkmopsuvz] [-a X,Y,W,H] [-C NAME] [-D DISPLAY] \
[-d SEC] [-e CMD] [-l STYLE] [-n OPTS] [-q NUM] [-S CMD] \
[-t NUM | GEOM] [FILE]
```
Here's an example of a suckless utility which follows the same style:
```
$ dmenu -h
usage: dmenu [-bfiv] [-l lines] [-p prompt] [-fn font] [-m monitor]
[-nb color] [-nf color] [-sb color] [-sf color] [-w windowid]
```
And an OpenBSD utility with the same style:
```
$ signify -h
signify: unknown option -- h
usage:  signify -C [-q] [-p pubkey] [-t keytype] -x sigfile [file ...]
signify -G [-n] [-c comment] -p pubkey -s seckey
signify -S [-enz] [-x sigfile] -s …
```

use the manual's synopsis as help text

---

CONTRIBUTING.md
TODO.md

CONTRIBUTING.md is now exclusively a tutorial on how to contribute to scrot, though it avoids duplicating the build instructions and how to acqure the dependencies by pointing to README.md and .cirrus.yml.
I didn't move the build instructions to CONTRIBUTING.md because they're also meant for package maintainers and savvy users.
The CONTRIBUTING.md section about looking for bug reports downstream was moved entirely to TODO.md.
I've also added a new section to TODO.md about changing the existing code to the new style.

overhaul CONTRIBUTING.md and TODO.md

---

configure.ac

This changes configure.ac to assume c89 functions exist.
Checking for them is pedantic and scrot is not compatible with C89 or pre-ANSI C, scrot is written in the newer C99 standard.
The more obtuse and roundabout the code is the harder it is to understand and maintain. Additionally, this will speed up the build a little as autotools is fairly slow.

assume c89 functions exist

---

src/main.c
src/options.c
src/options.h

This patch is a small refactor for options.c and its header.
A function had its name changed so a call in main.c had to be changed.
By using designated initializers, we can do away with one function and abbreviate the code without being cryptic.
This also replaces a preprocessor use with an enum, and renames a function to use a shorter name.

refactor options.c

---

src/main.c

If Xlib cannot get the image of the mouse cursor we can do nothing
more than report and continue with the screenshot.
Bug fixed: segmentation fault

Alert if mouse cursor image was not obtained

---

man/scrot.txt
src/main.c
src/options.c
src/scrot_selection.c
src/scrot_selection.h
src/selection_classic.c
src/selection_edge.c

Allows you to create a black(*) area in a full screen capture to hide information.
(*) Edit: the color of the area of the same color of the selection line, the default color of the selection line is gray
Add optional argument for option --select
You can indicate the action to perform with the selection area:
```
capture  Capture the selection area, this action is by default.
hide     Hide the selection area by drawing a color area over it.
Example:
$ scrot --select=hide
$ scrot -shide
$ scrot -s=hide
```

New feature: hide selection area

---

src/main.c

As argument to the sizeof operator.

Code style: use the identifier and not the type

---

src/selection_classic.c

Only for classic selection mode.
When the line color is black, the selection area is not drawn.
This happens because the function attribute for GC is GXxor and
the foreground and background color should not be 0.
See: 95bea6b2fa (New feature: hide selection area)

Do not assign black color to the foreground

---

src/main.c
src/selection_edge.c

This C routine is considered obsolete, nanosleep is used instead.

 Remove obsolete function: usleep

---

src/selection_edge.c

Selection mode: edge
In some selection areas, such as within a web browser, the selection border is captured.
To solve it, the delay is increased from 50ms to 80ms.

Increase delay to event unmap window

---

src/main.c
src/note.c
src/options.c

If conditions that have a body containing a single line, that's broken into multiple lines, should also use curly brackets.
However, there were a couple such if conditions without curly brackets so I just fixed that.

Fixed a couple of code style guideline violations

---

src/main.c
src/options.c
src/options.h

When I initially implemented the --file / -F option, the naming of the thumbnail was done in the options.c file, at the end of the options parsing function, by introducing an extra check if there is a filename and a thumbnail. However, I have felt that there must be a better way / place to do that.
I have since found out that in main.c after the parsing of the options, there is already a check if a filename exists and naming of both the thumbnail and the filename is done there. This felt like the perfect place.
So, from options.c, I removed:
```
if (opt.thumb && opt.outputFile)
opt.thumbFile = nameThumbnail(opt.outputFile);
```
In main.c I changed this:
```
if (!opt.outputFile) {
opt.outputFile = strdup("%Y-%m-%d-%H%M%S_$wx$h_scrot.png");
opt.thumbFile = …
```

File option cleanup

---

src/scrot_selection.c

An empty initializer list is a GNU extension. The Standard C way of initializing a struct with nulls is to initialize the first member with a 0, which implicitly null-initializes all the other members of the struct.
I've been playing with compiler flags and compiling scrot with several compilers in the hopes I catch something, this unnecessary usage of a GNU extension came up.

C99 forbids empty initializer braces, fill them

---

configure.ac

This patch adds checks for the presence of the warn() and warnx() functions, and it also adds a check for the presence of the sys/queue.h header.

check for more libbsd functions

---

src/Makefile.am
src/main.c
src/options.c
src/scrot.h
src/util.c
src/util.h

This patch adds an estrdup() fuction which is merely a strdup() which never returns NULL because it terminates execution on error. It replaces strdup() calls with the new function, none of the current strdup() calls check if the returned pointer is NULL.

add util.{c,h} with estrdup function and use it

---

src/selection_classic.c

Fix "--count --delay" rendering issue when not showing counting progress in terminal.
This happens when using the "--freeze" option and the "hide/hole/blur" selection modes with the classic line style.
In this scenario, the "--freeze" option acts twice, generating the failure.

Call XFlush after XUngrabServer

---

Makefile.am

Before this patch with --docdir=/usr/share/doc/scrot-1.7-r1 (example downstream
versioning for patches):
```
>>> /usr/share/doc/scrot-1.7-r1/
>>> /usr/share/doc/scrot-1.7-r1/README.md.bz2
>>> /usr/share/doc/scrot-1.7-r1/ChangeLog.bz2
>>> /usr/share/doc/scrot-1.7-r1/AUTHORS.bz2
>>> /usr/share/doc/scrot/
>>> /usr/share/doc/scrot/scrot.png
>>> /usr/share/doc/scrot/README.md.bz2
>>> /usr/share/doc/scrot/ChangeLog.bz2
>>> /usr/share/doc/scrot/AUTHORS.bz2
```
After:
```
>>> /usr/share/doc/scrot-1.7-r1/scrot.png
>>> /usr/share/doc/scrot-1.7-r1/README.md.bz2
>>> /usr/share/doc/scrot-1.7-r1/ChangeLog.bz2
>>> /usr/share/doc/scrot-1.7-r1/AUTHORS.bz2
```
This avoids installing duplicate files & installs them to the
same location but it's overridable by --docdir in ./configure which
helps downstreams. …

build: respect docdir

---

src/stamp-h.in

Autotools documentation has an "Automatic Remaking" chapter, as you can see at: https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.70/html_node/Automatic-Remaking.html
In it, there's a snippet about using a "stamp-h.in" file to "automatically update the configuration information when you change the configuration files" to quote the page, by adding a few rules to Makefile.in.
Except we don't have such rules in our Makefile.in, so we're not using that file. The file dates back to old scrot so maybe it was in use then, but it's not now.
This patch removes src/stamp-h.in.
I've skimmed the source tree a few times and I think that with this all the unused files will have been removed.

remove src/stamp-h.in

---

.cirrus.yml
.github/workflows/full-check.yml
README.md
configure.ac
src/Makefile.am
src/imlib.c
src/imlib.h
src/note.c
src/note.h
src/options.c
src/options.h
src/scrot.c
src/scrot.h
src/scrot_selection.c
src/scrot_selection.h
src/selection_classic.c
src/selection_classic.h
src/selection_edge.c
src/selection_edge.h
src/slist.h
src/util.c

This is a big change and it's doing a lot, I don't expect it to be perfect, but here's a summary and the idea:
- rename src/main.c to src/scrot.c
This isn't merely a pick on the filename. We have a src/scrot.h file (which is also the main offender for the tangled headers) containing the declarations of main.c (among others). To follow the typical C organization where a header's filename only differs from its corresponding .c file in the extension, either scrot.h needed to become main.h or main.c needed to become scrot.c. I follow the convention of naming the source file containing main() after the project, so I renamed main.c to scrot.c.
This actually included touching a few comments which mentioned a "main.c" file.
- untangle src/scrot.h
This file declared pretty much all of the scrot.c …

untangle headers

---

CONTRIBUTING.md

It seems the CI definitions only build against Debian Testing and Debian Unstable now, this patch removes the mention of Debian Oldstable.

remove reference to oldstable in CONTRIBUTING.md

---

.cirrus.yml
.github/workflows/full-check.yml

- Add Cygwin to the CI
This is mainly to test portability further.
Cygwin uses the newlib libc on top of Windows. The newlib libc implements a lot of BSD functions. It's a weird platform so maybe it'll catch a bug in the future.
- Add distcheck CI target
I noticed that in PR #175 @daltomi noticed the PR broke `make distcheck`, this could have been caught by the CI, now it will. I also noticed that the Github Actions CI was doing almost all of https://www.gnu.org/software/automake/manual/html_node/Checking-the-Distribution.html by hand, so the lines were deleted as `make distcheck` now fills their role.
- Bring the Cirrus CI in line with Github Actions
The Cirrus actions I wrote didn't run `scrot -v` or do the equivalent of `make distcheck`, now they do. I had to add the gzip package to …

small CI revamp

---

.cirrus.yml
.github/workflows/full-check.yml
README.md
configure.ac

Quoting
[GCC Documentation](https://gcc.gnu.org/wiki/LinkTimeOptimization):
> Link Time Optimization (LTO) gives GCC the capability of dumping its
> internal representation (GIMPLE) to disk, so that all the different
> compilation units that make up a single executable can be optimized as
> a single module. This expands the scope of inter-procedural
> optimizations to encompass the whole program (or, rather, everything
> that is visible at link time).
It also has the nice side effect of allowing warnings across translation
units, as attested by these internet blogs:
[gcc 8: link time and interprocedura optimization](https://hubicka.blogspot.com/2018/06/gcc-8-link-time-and-interprocedural.html)
[gnu link time optimization finds non-matching …

add link time optimization and warnings by default

---

src/note.c
src/note.h
src/options.c
src/scrot.c

- Reduce the scope of the ScrotNote structure by making it local to
note.c
- Reduces the '.bss' segment data by not defining the global ScrotNote
structure, it is now a pointer.

Improvements in the note option

---

src/scrot.c

Here's #192 but without the extra baggage.

remove last #ifdef

---

src/scrot_selection.c

the PIXEL_ARGB() macro would do an overwide shift if `int` is 16bits.
and in case of 32bit ints the result of the shift `a << 24` can
overflow, which is undefined behavior.
test case, (compile with UBSan):
$ ./configure CFLAGS="-fsanitize=undefined -g"
$ make
$ ./src/scrot -shide,some.png -l "opacity=254" -o /tmp/whatevr.png
scrot_selection.c:426:25: runtime error: left shift of 156 by 24 places cannot be represented in type 'int'
this patch also removes the PIXEL_* macros entirely, they weren't needed
because only the alpha changed, r,g,b was unchanged.

fix shift error

---

src/scrot.c

@N-R-K pointed out the deprecated type and revived interest in removing
the only usage of a VLA in this project.
See the discussion after #193 was merged.
I've tested taking a screenshot with and without a mouse cursor after applying this change, it worked fine.

remove VLA and imlib2's deprecated DATA32 type

---

configure.ac

Remove the forced bzip2 format and use only the default: gzip
Doc: make dist
Generate a ‘gzip’ tar archive of the distribution.
This is the only format enabled by default. 
By default, this rule makes gzip use a compression option of --best.
To make it use a different one, set the GZIP_ENV environment variable.
For example, ‘make dist-gzip GZIP_ENV=-7’.

Automake: Use default compression format

---

.cirrus.yml

`git blame` says I touched that file in 2022 too and forgot to update the copyright year, so I'm adding 2022 and 2023.
This fixes the recent MacOS build failures.

.cirrus.yml: Update MacOS CI and copyright year

---

README.md
configure.ac

Users expressed confusion when using the old "--without-libbsd" configure flag. Some assumed that it compiles scrot without libbsd, but it only made the build script error if libbsd is a dependency. This is useful to package maintainers: it gives them a yes/no answer on whether the library is a dependency on their system.
The old configure flag has been replaced by a more verbose "--enable-libbsd-feature-test".
See: https://github.com/resurrecting-open-source-projects/scrot/issues/208 https://github.com/resurrecting-open-source-projects/scrot/discussions/187
I've tested the yes/no paths using Alpine Linux and OpenBSD.

fix libbsd feature test confusion

---

FAQ
src/options.c

Until version v1.7 it would silently convert a floating point number to a zero(0). Which is an error since it allowed the user to believe that the value given to the option was correct, when it is not. Since version v1.8, the entered value is indicated with an error 'is not an integer'.

Indicate that the value is not an integer

---

src/options.c

just declare an array and use sizeof operator on it. less error prone this way.

do not hardcode string length

---

src/scrot.c

sleep() may end up waking up eariler than requested due to signals. so
use nanosleep() and deal with EINTR in case it happens.
since we want the output to be immediately shown, using stdio doesn't
make much sense. using dprintf to output straight to the file descriptor
allows us to skip having to manually flush every time.
otherwise, the countdown won't be visible when user is outputting the
image to stdout. for example commands like the following will end up
with a "corrupted" image due to the countdown being slipping in there.
scrot -d3 -c - | xclip -in -selection clipboard -target image/png
by outputting the countdown to stderr, the above command will work
properly.
for reference, `maim` also outputs it's countdown to stderr, not stdout.

Add scrotSleep and use dprintf

---

src/options.c

Noticed these while I was trying to add `--delay-select` for #221 
getopt_long manpage says:
| If all command-line options have been parsed, then getopt() returns -1.
it doesn't say anything about returning EOF. but since EOF is typically
defined as -1 it ended up working by accident.
getopt_long accepts NULL as longindex argument, so no need to pass a
dummy variable.

getopt_long() cleanup

---

src/scrot.c
src/scrot.h

Also moves the definition of the function so the functions in the source file are defined closer to the order in which they're called.

scrotGetWindowName(): change to internal linkage

---

man/scrot.txt

ref: https://man7.org/linux/man-pages/man7/man-pages.7.html

manpage: use conventional brackets to indicate optional argument

---

src/options.c
src/util.h

let the caller duplicate it if needed, allows for passing the return
value straight to optionsParseFileName()
also since STDOUT_FILENO is defined to be 1 there was no need to call
snprintf().
- - -
Includes the mem leak fix from #229

Simplify getPathOfStdout()

---

src/scrot.c
src/util.c
src/util.h

The imPrintf function currently is horribly inefficient due to `strlcat` having to recompute `strlen` on _every single call_ [^0].
The requirement of nul-terminator also makes for very awkward code like these:
https://github.com/resurrecting-open-source-projects/scrot/blob/5388fffd7be700834ee888ed129b2325c8ab1ef2/src/scrot.c#L684-L685
Instead just remember where to append, and grow the buffer dynamically if needed (which would enable properly fixing https://github.com/resurrecting-open-source-projects/scrot/issues/223). 
[^0]:  If the standard string copying functions [weren't idiotic](https://www.symas.com/post/the-sad-state-of-c-strings) then strcat (and friends) wouldn't even need to exist.

imPrintf: use dynamic buffer and concatenate efficiently

---

man/scrot.txt
src/options.c

the b prefix will indicate that the user wants the delay to be applied before the selection (if selection is active).
this also removes --delay-select, it was awkward to use and more lengthy than `-d b8`.

allow `b` prefix in --delay argument

---

man/scrot.txt
src/options.c
src/options.h
src/scrot.c

```
It allows to indicate the identifier of the window, value in
hexadecimal, to which to capture.
Ex: 'scrot --window 0x100000c'
```
Ex:
```fish
set WID $(xwininfo | grep "Window id:" | awk '{print $4}') && scrot --window $WID
```
Required parent branch: 23d587a ("Add delay to all capture options")

New option: --window

---

src/options.c

Sorry but this function has been bugging me ever since #220. I knew it could be better but I failed back then.
I've tested it with these commands:
```sh
src/scrot --thumb 50 test.png
src/scrot --thumb 50 test
src/scrot --thumb 50 te.st.png
```
As you can see, all the right files were created:
```console
$ git status
On branch briefer-namethumb
Your branch is up to date with 'origin/briefer-namethumb'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
te.st-thumb.png
te.st.png
test
test-thumb
test-thumb.png
test.png
nothing added to commit but untracked files present (use "git add" to track)
```

clean up optionsNameThumbnail()

---

src/scrot.c

when the last char is `$` or `\`, the `c` pointer would end up advancing past the string length.
additionally use the return value of strftime for determining the string length instead of checking for '\0'.
Fixes: https://github.com/resurrecting-open-source-projects/scrot/issues/252

imPrintf: avoid going out of bound

---

configure.ac
man/scrot.txt
src/options.c
src/options.h
src/scrot.c

Check the commit message for details.
This the extent of the testing I've done:
```console
$ src/scrot -F test test2
scrot: both the --file option and the FILE parameter were used
$ src/scrot -F test test2 test3
scrot: both the --file option and the FILE parameter were used
$ src/scrot test test2
scrot: extraneous non-option arguments: test2
$ src/scrot test test2 test3 test4
scrot: extraneous non-option arguments: test2 test3 test4
$ src/scrot "$(yes | tr -d '\n' | dd bs=251 count=1 2>/dev/null)".png
$ src/scrot "$(yes | tr -d '\n' | dd bs=256 count=1 2>/dev/null)".png
scrot: Saving to file yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy …
```

fix multiple bugs in output file handling

---

configure.ac

I haven't actually tested it on a CentOS 7 system because I don't have a spare system to try it on and OpenBSD's virtualization daemon is very limited, the daemon doesn't work with every Linux distribution.
Should fix #225.

fix compilation on CentOS 7

---

src/options.c

fixes a warning in the ubuntu CI
../../../src/options.c:542:47: warning: operand of ‘?:’ changes signedness from ‘long int’ to ‘size_t’ {aka ‘long unsigned int’} due to unsignedness of other operand [-Wsign-compare]
542 |     const size_t baseNameLength = extension ? extension-name : nameLength;

optionsNameThumbnail: fix sign integer warning

---

src/options.c

Alphabetically sort getopt_long()'s optstring, struct option array (by the short options), and switch statement's cases.
Align the text of all the members in our struct option array's initializer.
Remove 2 useless cases. getopt_long() will never return 0 with our usage, and if it does, the behavior of the 0 case isn't what we want. Also change the '?' case to default so scrot hard errors in the unlikelihood that our assumptions are broken, and remove the duplicate (and previously useless because it never happened) default.
Remove an useless comment (/* actions */).
Sort variable declarations by order of use.

getopt_long() style cleanup

---

src/scrot.c

the scrotGrab* functions do not necessarily set errno.
to reproduce run: `scrot -s` and then cancle the selection with keyboard press.

fix displaying incorrect error message

---

src/options.c

The comment explaining its usage from when we only had OptionsParseNum(), and its usage was incorrect.
Also split up a nearby line that was over 80 chars.

OptionsParseNumBase() small cleanup

---

man/scrot.txt
src/options.c
src/scrot.c

Relevant imlib documentation:
https://docs.enlightenment.org/api/imlib2/html/
CTRL+F "Imlib 2 Dynamic Filters"
The -S flag makes imlib filters available to the user. However, it's impossible to do this, because imlib filters can reference variables passed to `imlib_apply_filter()` via varargs, and there's no way in C to pass the right amount of varargs. Look up "[] operator" in the imlib documentation.
Additionally, this option may be the source of a security vulnerability. A malicious imlib script could decrement the stack pointer by using the right amount of imlib script [] operators. Varargs are typically implemented by popping values off the stack. By changing what the stack points to, the values of variables or the return address could be changed, the stack pointer could even be …

remove -S flag

---

src/options.c
src/scrot.c
src/scrot_selection.c
src/util.c

* else and else if are supposed to be on the same line as the closing brace: https://webkit.org/code-style-guidelines/#linebreaking-else-braces
* switch statement should have a space
* webkit style recommends using `!p` instead of `p == NULL`
* remove an unnecessary macro and use a local char array instead

style: fix some consistency issues

---

src/scrot_selection.c

strerror operates on errno values, not X error codes.

fix: faulty strerror call

---

man/scrot.txt

the --quality description was changed in fc27d9f but that description is not correct for lossless formats. correct the manpage description to reflect what actually happens.
Closes: https://github.com/resurrecting-open-source-projects/scrot/issues/277

manpage: correct description of quality

---

src/options.c
src/options.h
src/scrot.c
src/scrot_selection.c
src/scrot_selection.h

There are many cases in scrot where strings are unnecessarily duplicated. The goal of this patchset is to remove these.
Most of these strings also were never free-ed, so this also technically fixes some memory leaks (although in practice this isn't that big of an issue since scrot is a "one shot" program, not a long running process).
- - -
A couple other cases worth investigating:
```console
src/note.c:287:    return strndup(begin, length);
src/options.c:617:    opt.note = estrdup(optarg);
```
Also note: `opt.lineMode` is handled in #282.

Remove unnecessary string duplication

---

src/scrot.c

* execStr is allocated via imPrintf, so free it before returning.
* remove unnecessary `exit(0)` - simply let the control return back to
`main()` where it will do some cleanup and exit anyways.
* remove useless `errno = 0`.
* initialize execStr and ret immediately.
according to waitpid(3) manpage:
| This macro (WEXITSTATUS) should be employed only if WIFEXITED returned true.

scrotExecApp cleanup

---

src/options.c

the convention is for newer cli arg to overwrite the older one. however as of now, opt.delay_selection doesn't properly get cleared. to reproduce:
./scrot -d b3 -d 5 -s -c
the earlier `-d b3` makes it so that opt.delay_selection stays true even though the later `-d 5` should've overwritten it.

fix: reset delay_selection properly

---

man/scrot.txt

it's shorter, and not too difficult to figure out how it works even if you're unaware of it (e.g just trying out `--flag LIMIT`).
ref: https://en.wikipedia.org/wiki/Interval_(mathematics)

manpage: use mathametical range notation

---

src/options.c
src/options.h
src/scrot.c
src/scrot_selection.c
src/util.h

This will conflict with #257, has only been minimally tested, and there are other places in the code where it's useful but hasn't been put to use yet, so it remains a draft.
Old `nanosleep()` code (master) on OpenBSD:
New `clock_nanosleep()` code (this PR), falling back to a local `clock_nanosleep()` implementation on systems lacking this POSIX function like OpenBSD and OS X, running on OpenBSD: 
The timing error is consistently smaller across several runs. If you subtract the user and system runtime and the 60 second sleep from the real runtime, you get the timing error. It has been reduced by an order of magnitude here.

improve timing in `scrot --delay`

---

src/scrot.c

Fallout from https://github.com/resurrecting-open-source-projects/scrot/pull/261

don't get the remainder if nanosleep is interrupted

---

README.md

The last release of pkg-config was in 2017-03-20:
https://pkgconfig.freedesktop.org/releases/
pkgconf has silently replaced pkg-config in the wild. For instance, in Debian: https://packages.debian.org/sid/pkg-config
Let's recommend the maintained implementation.

README: pkg-config is abandoned, recommend pkgconf

---

README.md
man/scrot.txt

scrot's license has always been (as far as the git history goes at least) MIT-feh [0]. but the README and manpage incorrectly identified it as MIT-advertising [1].
so change it to MIT-feh. (note: the content of the license is still same, this is just fixing a misidentification.)
[0]: https://spdx.org/licenses/MIT-feh.html
[1]: https://spdx.org/licenses/MIT-advertising.html
Closes: https://github.com/resurrecting-open-source-projects/scrot/issues/310

fix: license name in README and manpage

---

src/selection_edge.c

* xeventUnmap() did not check the union type before reading from it.
* unmap event should always come, no need to sleep/retry 30 times.
* remove xeventUnmap() and waitUnmapWindowNotify() entirely. the main logic is short enough to inline directly at the call site.
* rather than unmapping the window, and then destroying it, destroy it directly and wait for the DestroyNotify event. (this may help with: https://github.com/resurrecting-open-source-projects/scrot/issues/284)
* compare window ID against `None` rather than `0`. no functional difference, but using `None` is more idiomatic for X11 things.

selectionEdgeDestroy: misc cleanups

---

src/scrot.c

this patch simply removes the fluff and indirection and shows what's actually going on already. since we never subscribed to visibility event, we're never going to receive it anyways and will end up sleeping the entire duration.
also reduce the sleep from ~300ms to ~160ms, which should be enough for local X server. (note: it's fine to call nanosleep in loop, it's just a fuzzy sleep, doesn't have to be exact).
ref: https://github.com/resurrecting-open-source-projects/scrot/issues/274

scrotGetGeometry: sleep explicitly

---

.github/workflows/full-check.yml

cppcheck is a decent static analyzer that can catch some interesting issues that compiler warnings (and sometimes even other analyzers) don't catch.
currently cppcheck doesn't find anything, but that's because I had mostly fixed it's finding very early on when I started contributing to scrot.
I've had cppcheck, along with gcc -fanalyzer and clang-tidy running locally for quite some time now. it will be worthwhile to add it to the CI so that it's findings can be visible to other contributors as well.
in the future, we might want to enable `-fanalyzer` and clang-tidy as well, but clang-tidy currently produces 3 warnings, 2 of which I've investigated and found to be false-positives (haven't investigated the 3rd one).
to run clang-tidy locally:
$ clang-tidy --quiet …

ci: add cppcheck for static analysis

---

.clang-tidy
.github/workflows/full-check.yml
src/scrot.c
src/scrot_selection.c

the list of checks as of now is fairly conservative.
one other check that might be worth enabling in the future:
* bugprone-narrowing-conversions: unfortunately it doesn't understand
the semantics of optionsParseNum() and thus produces way too much
noise.

ci: add clang-tidy

---

man/scrot.txt
src/options.c

reasons:
* The interface is clunky to use
* Requires Imlib2 to be built with "text" support (which adds additional dependency).
* It's better done via an actual image editing software
* No one seems to be using it, since no one objected towards removing it in the discussions thread.
ref: https://github.com/resurrecting-open-source-projects/scrot/discussions/207
ref: https://github.com/resurrecting-open-source-projects/scrot/issues/236

deprecate --note

---

configure.ac

When using default CFLAGS, we want only the CFLAGS that the compiler doesn't support to be excluded, not all of them.

improve the robustness of default CFLAGS

---

.github/workflows/full-check.yml

-fanalyzer used to throw out two warnings about memory leaks, but that seems to have been fixed with cc677e660daa53b3a8c60a18e0d0456eb322727a
also enables some aggressive gcc flags that aren't enabled by default even at -O3 (e.g graphite, ipa-pta).

ci: add aggressive gcc build with -fanalyzer

---

src/Makefile.am

Automake always uses {CPP,C}FLAGS to compile programs. We've been erroneously duplicating them into scrot_{C,CPP}FLAGS (per-target flags).
Ref: https://www.gnu.org/software/automake/manual/html_node/Flag-Variables-Ordering.html

src/Makefile.am: don't duplicate {CPP,C}FLAGS

---

src/options.c
src/scrot.c
src/scrot.h
src/scrot_selection.c
src/selection_edge.c
src/util.h

The `timespec` argument for nanosleep is awkward because it uses `ns` when we want to sleep for some `ms` instead. And `scrotWaitUntil` is awkward because it uses absolute time, instead of relative time.
Add `scrotWaitFor` which uses a relative time in `ms` and uses `scrotWaitUntil` internally.
CC: @guijan

Revise scrotWaitUntil interface

---

src/options.c

standard library functions are allowed to change errno even on success and thus setting errno to 0 before calling something typically doesn't do much (with exceptions such as strtoll() where it's documented recommendation to set errno to 0 before calling).
saving and restoring errno is typically done inside non-fatal signal handlers so that the resuming code isn't impacted by the clobbered errno. no reason to do it in a string to integer conversion routine.
also fix a small indentation issue.

remove dubious errno usage

---

.cirrus.yml
.github/workflows/full-check.yml
configure.ac
src/options.c

this adds support for EXTRA_CFLAGS, which seems to be a common convention to append additional cflags. e.g neomutt uses it, linux kernel used to use it.
Fixes: https://github.com/resurrecting-open-source-projects/scrot/issues/283

ci: add -Werror

---

src/scrot_selection.c
src/scrot_selection.h
src/selection_classic.c
src/selection_edge.c

This patch series removes some unnecessary allocations and indirections from the selection code. Everything should still continue working as usual, no change in functionality is intended.
The PR may also be better viewed as [individual commits](https://github.com/resurrecting-open-source-projects/scrot/pull/339/commits), the commit messages contain a bit more details and rationale.

selection: remove unnecessary allocations and indirections

---

src/scrot_selection.c

MotionNotify returns a xmotion type and KeyPress returns a xkey type not an xbutton type.
but since the top members of xbutton, xmotion and xkey are the exact same, it happened to work out by accident.
ref: https://www.x.org/releases/X11R7.7/doc/man/man3/XButtonEvent.3.xhtml

use the correct union type

---

man/scrot.txt

add some useful examples such as copying to clipboard, annotating text etc using other utilities along with scrot.

man: add examples of using scrot with other utilities

---

src/scrot.c

I don't have access to a SmartOS system, so I haven't tested it on SmartOS. I did test it on OpenBSD.
Fixes #346.

replace dprintf() calls to fix the SmartOS port

---

README.md
configure.ac

this avoids misleading people due to the issues described in #315.
and packagers can already check the output of the configure script or config.log to see if libbsd was checked for or not.
additionally, document which bsd extension we require in the README so that maintainers can make more informed decision (e.g using more lightweight `sys/queue.h` in musl instead of heavyweight libbsd).
ref: https://github.com/resurrecting-open-source-projects/scrot/issues/307
Fixes: https://github.com/resurrecting-open-source-projects/scrot/issues/315

configure.ac: remove unsound/misleading flag

---

man/scrot.txt
src/options.c
src/scrot.c
src/scrot.h

There's two commits, the first one dynamically grows the buffer to add the format to the extension.
The second commit makes things simpler by placing a limit on the format length, which is far greater any any existing image formats: https://en.wikipedia.org/wiki/Image_file_format
@guijan if you don't have any objection to the 2nd commit, then I'd like it keep it since it's simpler, avoids unnecessary "leak" and unnecessary failure points created by malloc.

fix: default extension if --format was used

---

src/scrot.c

Fixes: https://github.com/resurrecting-open-source-projects/scrot/issues/350

print a warning if output file was changed

---

man/scrot.txt
src/scrot.c

compositor doesn't seem to be needed and works fine without it. See: https://github.com/resurrecting-open-source-projects/scrot/pull/349#issuecomment-1606244433

don't require a compositor for -k

---

src/scrot_selection.c
src/scrot_selection.h

make functions which aren't used outside of the TU `static`.
additionally remove prototype for functions which have been removed: scrotSelectionDraw() scrotSelectionSetDefaultColorLine()

scrot_selection: use static functions

---

src/scrot.c

according to the XComposite manpage:
> No other XComposite functions (except XCompositeQueryExtension) may be
> called before XCompositeQueryVersion. If a client violates this rule,
> the effects of all subsequent XComposite calls that it makes are
> undefined.
fix it by calling XCompositeQueryVersion first.

fix undefined behavior with XComposite

---

src/options.c

currently `scrot ""` returns the following error message:
scrot: strftime returned 0
which isn't very useful. reject empty filenames early on with a more descriptive error message instead.

reject empty filename earlier rather than later

---

src/scrot.c

it's not really used by scrot, so avoid any unnecessary activities that might be caused by it.

disable imlib2's cache

---

src/options.c
src/options.h
src/scrot.c

currently `scrot -s -u` will end up taking a screenshot with selection enabled even though `-u` was specified later. this patch makes scrot follow the cli convention of the later option overwriting the earlier one.
fixes: https://github.com/resurrecting-open-source-projects/scrot/issues/264

better handle mutually exclusive options

---

src/scrot.c

imlib_create_image_from_ximage() expects x and y relative to the image itself and has no relation with the x,y position of the window.
which means we should pass 0 in both of them. otherwise, it'll try to read a width and height that's bigger than the image actually has.
buffer overflow was caught via AddressSanitizer.

fix: buffer overrun due to bad x,y

---

src/options.c

currently if scrot is invoked like `scrot --stack=weird=v` then it
treats as if the argument to --stack was `v` and skips over "weird="
entirely.
the code here seems to be trying to get rid of the '=' but there's no
need for it, getopt_long() will remove the '=' already.
avoid treating `scrot --stack=v_trailing_stuff` as valid.

more strict optional argument parsing

---

.github/workflows/full-check.yml
src/options.c
src/scrot.c

in a command like `scrot ~/.local/testfile` scrot will incorrectly think that `local/testfile` is the file extension and thus will try to use it as the output format.
ensure that the extension doesn't contain any slashes to avoid such issues.

fix: bad extension detection

---

man/scrot.txt

Previously, scrot's manual mentioned the manual `strftime(2)`, which, as far as
I know it is incorrect. According to the Linux manpage `man-pages(7)`,  section
number `2` is for system calls and not for library functions.
I attempted searching for the manual `strftime(2)` to no avail with the command
`man -s 2 --names-only --wildcard 'strftime(2)'` and there are no lines with
the word `strftime` in the file `/usr/include/asm/unistd_64.h`, which has
system call numbers.

Correct strftime manual section

---

src/scrot.c

additionally return EX_UNAVAILABLE [^0] if the child terminated abnormally or returned non-zero.
[^0]: https://man.freebsd.org/cgi/man.cgi?sektion=3&query=sysexits
Closes: https://github.com/resurrecting-open-source-projects/scrot/issues/271

don't return 0 on exec failure

---

src/selection_edge.c

current code treats opacity as [0, 100] even though the manpage documents it as being [0, 255].
Fixes: https://github.com/resurrecting-open-source-projects/scrot/issues/281

fix: incorrect line opacity mapping

---

src/options.c

avoids funny situations later down the line such as creating `/tmp/_000` when invoked as `scrot /tmp/`
Fixes: https://github.com/resurrecting-open-source-projects/scrot/issues/228

reject filenames with trailing slash

---

FAQ.md
src/scrot_selection.c
src/selection_edge.c

selection classic is still the default for many people who are using a compositor. adding a hacky sleep similar to selection edge seems to fix it on my end.
Fixes: https://github.com/resurrecting-open-source-projects/scrot/issues/284

add sleep to classic selection destroy as well

---

Makefile.am
README.md
TODO.md
etc/bash-completion/scrot
etc/zsh-completion/_scrot
man/scrot.txt
src/options.c

This adds a `--list-options` flag which outputs a specialized TSV of all the options intended to be used in shell completion scripts. A couple TODOs:

Add `--list-options` and shell completions

---

man/scrot.1
man/scrot.txt

The line in the man page for `-u, focused, --focussed` is not being rendered properly. Adding an extra space between the flags and the description in scrot.txt fixes this.
This does put it out of line with the rest of the descriptions...

(man page) add extra space to make -u line render as heading

---

src/scrot.c
src/scrot.h
src/scrot_selection.c
src/selection_classic.c

this patch makes a couple different changes:
* previously the grab/ungrab was happening inside of selection_classic::{create,destroy}. this meant that `--freeze` was ineffective when edge mode was used. the patch moves those calls outside of it, so that `--freeze` can work on edge mode as well.
* because the grab/ungrab was happening inside selection destroy, there were multiple races. one of them was that the server would be ungrabbed after selection was done but *before* the shot was captured. the sleep introduced in commit 93e475d widened the race window and made it more easily noticeable. the patch makes it so that we don't ungrab the server until the shot is actually taken.
Fixes: https://github.com/resurrecting-open-source-projects/scrot/issues/381

fix racy --freeze behavior

---

.cirrus.yml
.github/workflows/full-check.yml

the ci script is referenced in CONTRIBUTING.md as an example, so keep dependencies to a minimal.
also use meta-package like "build-base" on alpine instead of installing binutils, make etc seperately.

ci: don't install unnecessary deps

---

src/scrot_selection.c

otherwise it could stay grabbed for longer than intended.
Fixes: https://github.com/resurrecting-open-source-projects/scrot/issues/402

flush after ungrabbing server

---

src/scrot_selection.c
src/selection_classic.c

removes XFlush from selectionClassicDestroy as it's now redundant.
also changes discard argument to false, not sure why it was true to begin with.
Maybe-fixes: https://github.com/resurrecting-open-source-projects/scrot/issues/387

XSync after selection.destroy() not before

---

src/scrot_selection.c
src/scrot_selection.h
src/selection_classic.c
src/selection_edge.c

- return a value instead of out pointer
- remove scrotSelectionCreateNamedColor

simplify scrotSelectionGetLineColor()

---

.cirrus.yml
.github/workflows/full-check.yml
README.md
deps.pc
man/scrot.txt
src/scrot.c

xrandr is supposedly the [better replacement](https://wiki.archlinux.org/title/Multihead#Xinerama) for xinerama. On my system, no packages (other than scrot) use xinerama while there's a bunch using xrandr, so it's likely a more common dependency which is probably already installed too.
Alternatively, instead of replacing it we could offer a build time config switch allowing the user to select between xrandr and xinerama.

replace xinerama with xrandr

---

man/scrot.txt
src/scrot_selection.c

edge mode never used to work with -f until commit c60a26c.
and it seems to be causing a lot of artifacts. so don't default
to it if --freeze is active.
Ref: https://github.com/resurrecting-open-source-projects/scrot/issues/408

don't default to edge when --freeze is given

---

src/scrot.c
src/scrot_selection.c

currently it only rings it after certain cases but not all. move the bell ringing outside of grab mode specific code and into main() where it will be consistently rang in case of a successful capture regardless of grab mode.
Fixes: https://github.com/resurrecting-open-source-projects/scrot/issues/412

always ring the bell after taking the shot
