resurrecting-open-source-projects/scrot

man/scrot.1
man/scrot.txt
src/main.c
src/options.c

Format $t only if we can get the format

---

src/options.c

Ref: https://bugs.launchpad.net/ubuntu/+source/scrot/+bug/371784

Fix: scrot don't complain about invalid numeric argument

---

src/Makefile.am
src/imlib.c
src/main.c
src/options.c
src/options.h
src/scrot.h

https://bugs.launchpad.net/ubuntu/+source/scrot/+bug/1698375
TODO:

Capture mouse pointer

---

man/scrot.1
man/scrot.txt
src/main.c
src/options.c
src/options.h
src/scrot.h

It allows to freeze the screen when the selection is used: `--select`
New option: `--freeze` or `-f`
TODO:

Support freeze the screen.

---

src/imlib.c

The right thing in every X server program, to release acquired
resources.

Call XCloseDisplay on exit

---

src/main.c

This pull request solves an old problem of not properly handling temporarily unavailable resources (keyboard), more details in the links below:
- https://bbs.archlinux.org/viewtopic.php?id=86507
- https://mail.haskell.org/pipermail/xmonad/2011-September/011760.html
- https://lists.suckless.org/dev/1108/9179.html
--ctarbide

retry to grab the keyboard for 1s in 50ms intervals if it is still

---

src/scrot_selection.c
src/scrot_selection.h
src/selection_classic.c
src/selection_classic.h
src/selection_edge.c
src/selection_edge.h

See comment:
https://github.com/resurrecting-open-source-projects/scrot/commit/94e969616e1f576488c8a18c049e48dd9dc21e6f#r44050230

Refactoring: clarify authorship

---

src/main.c

 Fix the capture of the edge of the focused window

---

man/scrot.txt
src/main.c
src/options.c

I resume the PR: `Resize the selection with the arrow keys` #33
[Preview GIF ](https://mega.nz/file/UdBg1DzY#48PXGcIaCNiV2ORy3y0cu9HHaFf9qmYymjedq9UWQS0) (Sorry but I couldn't upload an animated GIF here, maybe going back to the 80's I can give it a try)

Resize the selection with the arrow keys

---

src/selection_edge.c

Avoid capturing the selection box.
It may happen that if you drag and drop very quickly, scrot captures the image
while the screen has not yet finished updating and more when using a compositor.

Selection edge: wait UnmapNotify event

---

src/main.c

Fix selection area when it reaches the end of screen

---

src/main.c

Enhancement commit: ace605a
```bash
./scrot --select --pointer --delay 3 --count
```
Ref.: https://github.com/thenaterhood/gscreenshot/issues/115

Record pointer when selecting an area with delay

---

src/Makefile.am

Makefile.am: Fixed include file name slist.h

---

src/main.c
src/note.c
src/scrot_selection.c
src/scrot_selection.h
src/selection_edge.c

Fix the warnings indicate by compilers

---

src/options.c
src/options.h

- Long form : --debug-devel
- Short form: +
Closes: #108

Remove unused argument option: debug-level

---

src/options.c

Replace the conditional with strlen.

Use strndup to limit string

---

src/imlib.c
src/main.c
src/note.c
src/options.c
src/scrot_selection.c
src/selection_classic.c
src/selection_edge.c

Files:
main.c
imlib.c
note.c
options.c
scrot_selection.c
selection_classic.c
selection_edge.c
~~TODO: main.c~~

Use err and warn functions

---

src/main.c

Rename local variable that has a global name

Fixed shadow variable: extern Window root

---

man/scrot.txt
src/imlib.c
src/imlib.h
src/options.h
src/scrot.c
src/scrot.h
src/scrot_selection.c

The FILE parameters can take a new format specifier: $W
The name of the window (only for --select and --focused)
Ex:
$ scrot --focused mytitle$W.png

Add new format specifier: $W

---

man/scrot.txt
src/options.c

Options: --select --stack
These options optionally take parameters.

Fix help and manpage

---

src/scrot.c

Additional context provided in each commit message.

Fix some leak and bad free

---

FAQ
Makefile.am

Add FAQ file to project

---

src/note.c
src/options.c
src/options.h
src/scrot.c
src/scrot_selection.c
src/scrot_selection.h
src/selection_edge.c

This change also comes with some under the hood modifications to how args are handled.
This is a continuation of #200.
I've only gone as far as getting a build success, I haven't actually tested the changes. 
I'm leaving it a draft, I'm going to bed soon.

add informative error messages when parsing args

---

Makefile.am
README.md

* Add some files to bootstrapped tarballs.
* Improve build and install instructions.

Improve make-dist

---

src/scrot.c

Now the `--delay` option works for all capture options.

Add delay to all capture options

---

man/scrot.txt
src/options.c
src/options.h
src/scrot.c

Fixes #216 and documents this previously undocumented feature.

restore "keep ratio" functionality in --thumb

---

src/options.c
src/options.h
src/scrot.c

I've carefully read the Xlib manuals and some more, but this PR should be reviewed by someone more familiar with X programming.

fix multiple bugs in scrot's -C option

---

man/scrot.txt
src/options.c
src/options.h
src/scrot_selection.c

multiple users have expressed wanting to have the selection occur after the delay. this adds a flag which provides that behavior.
Closes: https://github.com/resurrecting-open-source-projects/scrot/issues/221

add --delay-select

---

man/scrot.txt
src/options.c
src/options.h
src/scrot.c

Add --format flag

---

configure.ac
src/scrot_selection.c

See each commit message for more details.

scrotSelectionGetUserSel() cleanup

---

src/options.c
src/options.h
src/scrot.c
src/scrot_selection.c

use standard `bool` instead using `int` as bool.
Closes: https://github.com/resurrecting-open-source-projects/scrot/issues/260

boolify opt members

---

configure.ac

More details in each commit message.

configure.ac: misc tweaks

---

.cirrus.yml
.github/workflows/full-check.yml

It uses the GNU preprocessor and linker, but it will help us with not depending on GCC too much.

add the TCC compiler to CI

---

src/scrot.c
src/scrot.h
src/scrot_selection.c

Additional details in commit messages.

Error check some imlib2 create image calls

---

src/scrot.c

this avoids unnecessary limit on the filename length (at the cost of creating new failure points due to dynamic allocations).
the biggest annoyance, and the reason why an additional dynamically allocated buffer was necessary, is the fact that strftime() doesn't have a way to distinguish between valid 0 return vs 0 return due to small buffer.
prepending a useless '.' in the format buffer and skipping over it later on solves this issue since it can no longer "validly" return 0.
Fixes: https://github.com/resurrecting-open-source-projects/scrot/issues/223

imPrintf: use dynamic buffer for strftime

---

src/scrot_selection.h
src/selection_edge.c

Closes: https://github.com/resurrecting-open-source-projects/scrot/issues/389

fix: don't try to unmap a window that isn't mapped

---

.cirrus.yml

The naming scheme in the images changed.

Update FreeBSD CI image to 14.2
